### ISSUE TITLE
Creative commons licensing?

### ISSUE THREAD

**Issue by bearloga** [wikimedia-research/survey-interval-responses#2]
Looking through the differences licensing options in https://rstudio.github.io/distill/metadata.html#creative-commons

Should we make this available under CC BY? I'm fine with including the share alike part but also okay not including it.

**Comment by Dpananos** [comment]
Hmm Hadn't thought about licensing.  I think the fact that " This is the most accommodating of licenses offered." makes it a good choice.

Let's do CC BY.

**Comment by Dpananos** [comment]
Closed prematurely.  Let's add the license and then close.
